### PR TITLE
Alter to XML Serialization

### PR DESCRIPTION
**Pull request by HuangFuSL**
Altered the serialization method from binary to XML.

### CODE REVIEW

**Comment by Strdate** [comment]
I will make a few changes and merge it, hopefully later this week

**Comment by Strdate** [comment]
In the end, I've decided to use JSON instead. Sorry for the inconvenience. It should be finished in a few days. Anyway, I'll let you know.

**Comment by HuangFuSL** [comment]
That's okay, as Python has native JSON support. It would be not so hard to adjust my code.

**Comment by Strdate** [comment]
Closing, see https://github.com/Strdate/PythonConsole/pull/11

**Pull request closed without merging**
